#!/usr/bin/bash

DIR=$1

#argument check
if [[ "$#" -lt "1" ]]; then
	echo "Not enought arguments" >&2
	exit 12
elif [[ "$#" -gt "1" ]]; then
	echo "Too many arguments" >&2
	exit 13
fi

#directory check
if [ -d "$DIR" ]; then
	echo "Directory:OK"
else
	echo "Directory:ERR" >&2
	exit 14
fi

#remove
if rm -f $DIR*.bak $DIR*.tmp $DIR*.backup; then
	echo "Remove:Done"
else
	echo "Remove:ERR" >&2
	exit 15
fi
